apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9000        # Внешний доступ через 9000
      targetPort: 8000  # Направляем на внутренний порт 8000
  type: ClusterIP